version: '2'
services:
  php_apache:
    build: docker/php
    ports:
      - 80
    volumes:
      - .:/var/www
  db:
    image: mariadb
    environment:
      MYSQL_USER: expresso-php
      MYSQL_PASSWORD: expresso-php
      MYSQL_DATABASE: expresso-php
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 80
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
## persistent data volume for mysql data
  dbdata:
    driver: local
    
